/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      colors: {
        'on-background': '#151c27',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#003ea8',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-surface-variant': '#434655',
        'surface-tint': '#0053db',
        'inverse-on-surface': '#ebf1ff',
        'surface-container-lowest': '#ffffff',
        'secondary': '#006c49',
        'surface-container-highest': '#dce2f3',
        'surface-container-low': '#f0f3ff',
        outline: '#737686',
        'on-tertiary-container': '#ffede6',
        'on-secondary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#7d2d00',
        'surface-bright': '#f9f9ff',
        surface: '#f9f9ff',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-container': '#eeefff',
        'surface-container-high': '#e2e8f8',
        'on-tertiary-fixed': '#360f00',
        tertiary: '#943700',
        background: '#f9f9ff',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary-container': '#00714d',
        'on-surface': '#151c27',
        'tertiary-container': '#bc4800',
        'primary-container': '#2563eb',
        'outline-variant': '#c3c6d7',
        'surface-container': '#e7eefe',
        'inverse-surface': '#2a313d',
        'primary-fixed': '#dbe1ff',
        'surface-dim': '#d3daea',
        error: '#ba1a1a',
        'primary-fixed-dim': '#b4c5ff',
        'tertiary-fixed': '#ffdbcd',
        primary: '#004ac6',
        'secondary-container': '#6cf8bb',
        'secondary-fixed': '#6ffbbe',
        'surface-variant': '#dce2f3',
        'on-secondary-fixed-variant': '#005236',
        'inverse-primary': '#b4c5ff',
        'tertiary-fixed-dim': '#ffb596',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00174b',
        ink: {
          950: '#070710',
          900: '#0b0b16',
          800: '#12121f',
          700: '#1b1b2e',
        },
        accent: {
          DEFAULT: '#7c5cff',
          400: '#9b7cff',
          500: '#7c5cff',
          600: '#6a3dff',
        },
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '24px',
        'container-max': '1200px',
        'margin-desktop': '40px',
        'stack-sm': '8px',
        unit: '8px',
        'stack-md': '16px',
        'stack-xs': '4px',
        'stack-lg': '24px',
        'stack-xl': '48px',
      },
      fontSize: {
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
      boxShadow: {
        glow: '0 0 0 1px rgba(124,92,255,0.35), 0 12px 40px -8px rgba(124,92,255,0.5)',
        'glow-soft': '0 8px 30px -8px rgba(124,92,255,0.35)',
        card: '0 20px 60px -20px rgba(0,0,0,0.5)',
      },
      keyframes: {
        shimmer: { '100%': { transform: 'translateX(100%)' } },
        'gradient-pan': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.6s infinite',
        'gradient-pan': 'gradient-pan 6s ease infinite',
        float: 'float 6s ease-in-out infinite',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
